# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'TwiterDemo' do
pod 'AFNetworking', '~> 3.0'
pod 'STTwitter'
pod 'SBJson', '~> 4.0.0'
end

target 'TwiterDemoTests' do
pod 'AFNetworking', '~> 3.0'
end

target 'TwiterDemoUITests' do

end

